### ISSUE TITLE
Command "api.raml" is not defined.

### ISSUE THREAD

**Issue by ddossot** [raml-leanlabsio/raml2html#1]
When I run: `raml2html.phar -i api.raml -o /tmp/api.html`

I receive:
<pre>                     
  [InvalidArgumentException]          
  Command "api.raml" is not defined.  
</pre>                             

although the `api.raml` file exists...

**Comment by cnam** [comment]
Hello, @ddossot 

Your need execute command  ```raml2html.phar generate -i api.raml -o /tmp/api.html```

**Comment by ddossot** [comment]
Oh boy.

<img src="http://vignette2.wikia.nocookie.net/transformers-legends/images/c/c4/Triple-facepalm.jpg"/>

Sorry.

**Comment by ddossot** [comment]
I thought I was using the other HTML generator (ie `raml2html -i api.raml -o /tmp/api.html`, no command needed like `generate`)... tool confusion :sob:
