### ISSUE TITLE
HTML Output of release 0.0.6 broken

### ISSUE THREAD

**Issue by ravage84** [raml-leanlabsio/raml2html#16]
When I generate the HTML for my RAML with release 0.0.5, it generates me a working API documentation.
When I try it with the new release 0.0.6, it's broken.

**Comment by cnam** [comment]
Hello @ravage84. What error are you see?

**Comment by ravage84** [comment]
Odd, I can't reproduce it anymore. If I can reproduce it again, I'll reopen this again. Thanks!
